steps:
  # Step 1: Install Terraform
  - name: hashicorp/terraform:latest
    entrypoint: sh
    args:
      - "-c"
      - |
        terraform init
        terraform validate

  # Step 2: Apply Terraform changes
  - name: hashicorp/terraform:latest
    args: ["apply", "-auto-approve"]

timeout: "1200s"  # Increase timeout if needed
